### PR TITLE
Change focus transition animation to resolve icon drawing issue

### PR DESCRIPTION
**Pull request by kgilmer**
Fixes https://github.com/EliverLara/Nordic/issues/8 on my computer.

I am new to GTK theme development so this may be the entirely wrong way to fix this issue.  I'm happy to update the PR as needed.

### CODE REVIEW

**Comment by EliverLara** [comment]
Thanks for providing a fix! I'll check how it looks on my session in order to merge it.

**Comment by EliverLara** [comment]
@kgilmer Could you make me the big favor of checking if your solution applies to [this](https://github.com/EliverLara/Sweet/issues/21)  issue as well? I would really appreciate it

**Comment by kgilmer** [comment]
Yep when I get back home I'll take a look. :)

**Comment by kgilmer** [comment]
Based on the screenshots I would say it's the same issue.  I'm using GNOME 3.32.2 and Ubuntu so not exactly the same setup but the UI bug appears exactly the same.

**Comment by kgilmer** [comment]
Hi @EliverLara , have you had a chance to review this yet?  I'd like to package the change if you agree it's correct.

**Comment by EliverLara** [comment]
Yes, it looks good, I forgot to merge it

**Comment by kgilmer** [comment]
Thank you @EliverLara !  How can I replicate your release zips?  Is it just running ` sass gtk.scss gtk.css` in the `gtk-3.0` directory or is there more to it?

**Comment by EliverLara** [comment]
Yeah, and also recompile the gtk-dark

**Comment by kgilmer** [comment]
Hi there!
 
 Find your next opportunity at an event of your interest
 
 
 
 
 
 10times is the world's largest business event platform to find events,
business conferences, trade shows, global seminars, networking meets and
workshops.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 Events near me
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 Connect with 40m+ event goers world wide.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 300k business events from around the globe.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 Professionals from more than 100 industries.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 Network with event-goers from more than 200 countries & 8000 cities.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 For any queries, reach out to Helpdesk
 
 
 
 
 
 
 Download our official Apps
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 | Manage Email Subscription

Unsubscribe From This List http://links.10times.com/asm/unsubscribe/?user_id=1002061&data=0WG_lHNH60BKciCkqCBVmgyVmjMmgG9IUfowZDVXGMvBW9dN8UpLQku8hffhIWU7ouRu_8_Q_9_vFK9kKmnS1QpKIIMQJwigSCQX3h3rfW8z9ZX4aiS1DKaKf55F_8U51-BHXQMzg_37vCIs8M8bbVVW4XwXatQrgQAHhNdZs2Vyb3WFlb_mg2G9kw0c4aQ8xPzRqygkV7MoCpS5XRuSlGtEKDMT6UTAUoQciEnOLIBDyUXRrUcouQv4jbzWpqe2jIxL6he4FyyKKkpp7ONLKRVXeRtWEOJjLr2YXX2iJAOmSYaa2kFIEV9_ZsIsSCSCd6sikjxgypAMqgmfZwMEpsqzesTrrhowpdNUPTGrUbO-_V4wYgIm6lP5iBaTn7LjyTJXAMZcH-k7-slDZwjEyBsAxAQe-aENh12snPNE8a23J6YN4EAKmQfpMmkXVMbamMI1fRu6KlrUxLUGmRSPYQ3zYlOTbXKKtqwo0sgcf57jVyjWGiaDwlxY45uTTdy37aDgxVfDsdaPwYG5hTr2q7h-CbOkIeEqLzqTBmWpZuM= | Manage Email Preferences http://links.10times.com/asm/?user_id=1002061&data=l5EvIqrOigxBm4hoUW-mBIWJJwg5vcKzeZtwW_IOyu-O2WiiG4eR9D8WiRKA1lgzRX7EfA-DyVpBnyYx8jYtKNa03UsIk5dRz85wFIIkPFX2UsjkBO7kIcpX1yOPqZXMwS3KK_q1wI4H7KgTu7VE5fXCDZxE509f-VOfN2J7DcDtIiTyEZ1zaAJ5C_L6F2R-Ke9HmJ1RT3JvlzmFc4aPTc8eP__vkCO-MkOn7YarggTvuO9mlMcCEgKOv9ktZzTwwZFlEuAWlOaUGe1AYtkBtGrbTf4j_Ks2VS4OzFuOTJ79pAFble4Fe_-q9vn0FjJp_UQqdDAgS9PkIT5EsxLs5CM9_7tyyOd530d_056iA0cph65rulJa_JfBu6p1Y37jdYjiwmg0BMBwB3LUA7Fw26rwFmHfPZzSprbg3F_x38-hboq_nBGpQZp5WgVSR7rGCBS5iRMQVpqTh3EVWEZjWKli9gGOQ7dMTOuL1O9KP8GlaOXjpgIi4RBbXj9cS8zIR6GAAqq2W2QUQe26WWPifw==

**Pull request merged**
